const FETCH_CAST_INFO_REQUEST = 'FETCH_CAST_INFO_REQUEST'
const FETCH_CAST_INFO_SUCCESS = 'FETCH_CAST_INFO_SUCCESS'
const FETCH_CAST_INFO_FAILURE = 'FETCH_CAST_INFO_FAILURE'
export {
    FETCH_CAST_INFO_REQUEST,
    FETCH_CAST_INFO_SUCCESS,
    FETCH_CAST_INFO_FAILURE
}