const FETCH_MOVIE_INFO_REQUEST = 'FETCH_MOVIE_INFO_REQUEST'
const FETCH_MOVIE_INFO_SUCCESS = 'FETCH_MOVIE_INFO_SUCCESS'
const FETCH_MOVIE_INFO_FAILURE = 'FETCH_MOVIE_INFO_FAILURE'
export {
    FETCH_MOVIE_INFO_REQUEST,
    FETCH_MOVIE_INFO_SUCCESS,
    FETCH_MOVIE_INFO_FAILURE
}