const FETCH_PERSON_INFO_REQUEST = 'FETCH_PERSON_INFO_REQUEST'
const FETCH_PERSON_INFO_SUCCESS = 'FETCH_PERSON_INFO_SUCCESS'
const FETCH_PERSON_INFO_FAILURE = 'FETCH_PERSON_INFO_FAILURE'
const FETCH_PERSON_EXT_REQUEST = 'FETCH_PERSON_EXT_REQUEST'
const FETCH_PERSON_EXT_SUCCESS = 'FETCH_PERSON_EXT_SUCCESS'
const FETCH_PERSON_EXT_FAILURE = 'FETCH_PERSON_EXT_FAILURE'
const FETCH_PERSON_MOVIE_CREDIT_REQUEST = 'FETCH_PERSON_MOVIE_CREDIT_REQUEST'
const FETCH_PERSON_MOVIE_CREDIT_SUCCESS = 'FETCH_PERSON_MOVIE_CREDIT_SUCCESS'
const FETCH_PERSON_MOVIE_CREDIT_FAILURE = 'FETCH_PERSON_MOVIE_CREDIT_FAILURE'
export {
    FETCH_PERSON_INFO_REQUEST,
    FETCH_PERSON_INFO_SUCCESS,
    FETCH_PERSON_INFO_FAILURE,
    FETCH_PERSON_EXT_REQUEST,
    FETCH_PERSON_EXT_SUCCESS,
    FETCH_PERSON_EXT_FAILURE,
    FETCH_PERSON_MOVIE_CREDIT_REQUEST,
    FETCH_PERSON_MOVIE_CREDIT_SUCCESS,
    FETCH_PERSON_MOVIE_CREDIT_FAILURE
}