 const FETCH_POPULAR_MOVIE_REQUEST = 'FETCH_POPULAR_MOVIE_REQUEST';
 const FETCH_POPULAR_MOVIE_SUCCESS = 'FETCH_POPULAR_MOVIE_SUCCESS';
 const FETCH_POPULAR_MOVIE_FAILURE = 'FETCH_POPULAR_MOVIE_FAILURE';

 export {
     FETCH_POPULAR_MOVIE_REQUEST,
     FETCH_POPULAR_MOVIE_SUCCESS,
     FETCH_POPULAR_MOVIE_FAILURE
 }